prefix text: <http://e-editiones.ch/ontology/text#>
prefix language: <http://e-editiones.ch/ontology/language#>
prefix text-expression: <http://e-editiones.ch/ontology/text-expression#>
prefix teaching: <http://e-editiones.ch/ontology/teaching#>
prefix prosodic-structure: <http://e-editiones.ch/ontology/prosodic-structure#>
prefix publishing: <http://e-editiones.ch/ontology/publishing#>
prefix delille: <http://e-editiones.ch/ontology/delille#>
prefix delille-pd: <http://e-editiones.ch/project/data/delille#>
prefix delille-research: <http://e-editiones.ch/ontology/delille-research#>
prefix calendar: <http://e-editiones.ch/ontology/calendar#>


# RETRIEVE CITATIONS PER BOOK TYPE PER YEAR:
# if add distinct does not retrieve distinct books, but distinct citations

SELECT
  ?publicationYear ?publicationPeriod 

  (COUNT( ?dictionary) AS ?Dictionnaires)
  (COUNT( ?anthologyOrManual) AS ?Anthologies_et_manuels)
  (COUNT( ?Science_et_vulgarisation) AS ?Science_et_vulgarisation)
  (COUNT( ?catalogue) AS ?Autres)

  # All Ouvrages littéraires
  (COUNT( ?Textes_en_vers) AS ?Textes_en_vers)
  (COUNT( ?Roman___récit_fictionnel) AS ?Roman___récit_fictionnel)
  (COUNT( ?Esthétique___poétique___histoire_littéraire) AS ?Esthétique___poétique___histoire_littéraire)
  (COUNT( ?Mémoires___biographies___histoire___etc) AS ?Mémoires___biographies___histoire___etc)
  (COUNT( ?essayOrPanoramicLiteraryOrPhilosophicOrHumanitiesExpression) AS ?Autres_essais)

  ((?Textes_en_vers+?Roman___récit_fictionnel+?Esthétique___poétique___histoire_littéraire+?Mémoires___biographies___histoire___etc+?Autres_essais) AS ?Ouvrages_littéraires)



    
  
WHERE {
  ?rhymingVerse
    a prosodic-structure:RhymingVerse;
    prosodic-structure:verseHasOrdinalNumeral ?verseOrdinalNumeral.
  
   {
    ?rhymingVerse ?p ?dictionary.
    FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
    ?dictionary a delille:Dictionary .
    ?dictionary publishing:isPublishedIn ?publication.
    MINUS {?dictionary a delille:Article}
    OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }
  UNION {
        ?rhymingVerse ?p ?anthologyOrManual.
    FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
    ?anthologyOrManual a delille:AnthologyOrManual .
    ?anthologyOrManual publishing:isPublishedIn ?publication.
    MINUS {?anthologyOrManual a delille:Article}
    OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }
  UNION {
        ?rhymingVerse ?p ?Science_et_vulgarisation.
        FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn, text:hasPasticheIn ) )
        ?Science_et_vulgarisation a delille:ScientificOrVulgarizedExpression .
        ?Science_et_vulgarisation publishing:isPublishedIn ?publication.
        MINUS {?Science_et_vulgarisation a delille:Article}
        OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }
  UNION {
        ?rhymingVerse ?p ?catalogue.
        FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
        ?catalogue a delille:Catalogue .
        ?catalogue publishing:isPublishedIn ?publication.
        MINUS {?catalogue a delille:Article}
        OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }



  UNION {
        ?rhymingVerse ?p ?Textes_en_vers.
        FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn, text:isPlagiarisedIn, text:isAlludedToIn, text:hasPasticheIn ) )
        ?Textes_en_vers a delille:PoemOrVersePlay .
        ?Textes_en_vers publishing:isPublishedIn ?publication.
        MINUS {?Textes_en_vers a delille:Article}
        OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }
  UNION {
        ?rhymingVerse ?p ?Roman___récit_fictionnel.
        FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
        ?Roman___récit_fictionnel a delille:Novel .
        ?Roman___récit_fictionnel publishing:isPublishedIn ?publication.
        MINUS {?Roman___récit_fictionnel a delille:Article}
        OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }
  
  UNION {
        ?rhymingVerse ?p ?essayOrPanoramicLiteraryOrPhilosophicOrHumanitiesExpression.
        FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
        ?essayOrPanoramicLiteraryOrPhilosophicOrHumanitiesExpression a delille:EssayOrPanoramicLiteraryOrPhilosophicOrHumanitiesExpression .
        ?essayOrPanoramicLiteraryOrPhilosophicOrHumanitiesExpression publishing:isPublishedIn ?publication.
        OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }
  UNION {
        ?rhymingVerse ?p ?Esthétique___poétique___histoire_littéraire.
        FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
        ?Esthétique___poétique___histoire_littéraire a delille:LiteraryScientificExpression .
        ?Esthétique___poétique___histoire_littéraire publishing:isPublishedIn ?publication.
        MINUS {?Esthétique___poétique___histoire_littéraire a delille:Article}
        OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }

  UNION {
        ?rhymingVerse ?p ?Mémoires___biographies___histoire___etc.
        FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
        ?Mémoires___biographies___histoire___etc a delille:LiteraryNonfictionExpression .
        ?Mémoires___biographies___histoire___etc publishing:isPublishedIn ?publication.
        MINUS {?Mémoires___biographies___histoire___etc a delille:Article}
        OPTIONAL {
          ?publication publishing:hasYearPeriod ?YearPeriod . 
          ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
          BIND ( (year(?gregorianYear)) AS ?publicationPeriod )
          BIND (?publicationPeriod AS ?publicationYear)
        }
        OPTIONAL {
          ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
          ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                                  publishing:hasEndYearPeriod ?endYearPeriod .
          ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
          ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
          BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?publicationPeriod)
          BIND ((year(?gregorianStartYear)) AS ?publicationYear)
        }
  }
}  

GROUP BY ?publicationYear ?publicationPeriod 
ORDER BY ?publicationYear