prefix text: <http://e-editiones.ch/ontology/text#>
prefix language: <http://e-editiones.ch/ontology/language#>
prefix text-expression: <http://e-editiones.ch/ontology/text-expression#>
prefix teaching: <http://e-editiones.ch/ontology/teaching#>
prefix prosodic-structure: <http://e-editiones.ch/ontology/prosodic-structure#>
prefix publishing: <http://e-editiones.ch/ontology/publishing#>
prefix delille: <http://e-editiones.ch/ontology/delille#>
prefix delille-pd: <http://e-editiones.ch/project/data/delille#>
prefix delille-research: <http://e-editiones.ch/ontology/delille-research#>
prefix calendar: <http://e-editiones.ch/ontology/calendar#>


# RETRIEVE CITATIONS PER BOOK TYPE PER YEAR:
# if add distinct does not retrieve distinct books, but distinct citations

SELECT
  ?citationYear

  (COUNT( ?dictionary) AS ?dictionaryCount)

    
  
WHERE {
  ?rhymingVerse
    a prosodic-structure:RhymingVerse;
    prosodic-structure:verseHasOrdinalNumeral ?verseOrdinalNumeral.
  
   
    ?rhymingVerse ?p ?dictionary.
    FILTER (?p IN (text:isCitedIn, delille-research:isCitedTwiceIn, delille-research:isCitedThreeTimesIn, delille-research:isCitedFourTimesIn, delille-research:isCitedFiveTimesIn ) )
    ?dictionary a delille:Dictionary .
    ?dictionary publishing:isPublishedIn ?publication.


    OPTIONAL {
    ?publication publishing:hasYearPeriod ?YearPeriod . 
    ?YearPeriod calendar:hasGregorianStartDate ?gregorianYear .
    BIND ( (year(?gregorianYear)) AS ?citationYear )
  }

  OPTIONAL {
    ?publication publishing:hasPartitionedPublishing ?partitionedPublication .
    ?partitionedPublication publishing:hasStartYearPeriod ?startYearPeriod ;
                            publishing:hasEndYearPeriod ?endYearPeriod .
    ?startYearPeriod calendar:hasGregorianStartDate ?gregorianStartYear.
    ?endYearPeriod calendar:hasGregorianEndDate ?gregorianEndYear.
    BIND ( (CONCAT(STR(year(?gregorianStartYear)), '-', (STR(year(?gregorianEndYear))))) AS ?citationYear)
  }  
  
  
	
}
    
  

GROUP BY ?citationYear
ORDER BY ?citationYear