PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX document: <http://e-editiones.ch/ontology/document#>
PREFIX electronic-information: <http://e-editiones.ch/ontology/electronic-information#>
PREFIX delille-po: <http://e-editiones.ch/ontology/delille#>
PREFIX delille-pd: <http://e-editiones.ch/ontology/delille#>

SELECT ?desc
WHERE {
  ?page a electronic-information:HypertextPage. # electronic-information:HypertextStartPage
  ?page	rdfs:label 'projet'. # 'start'
  ?page	document:hasContentLiteral ?desc.
}