PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX event: <http://e-editiones.ch/ontology/event#>
PREFIX human: <http://e-editiones.ch/ontology/human#>
PREFIX language: <http://e-editiones.ch/ontology/language#>
PREFIX calendar: <http://e-editiones.ch/ontology/calendar#>
PREFIX text: <http://e-editiones.ch/ontology/text#>
PREFIX text-expression: <http://e-editiones.ch/ontology/text-expression#>
PREFIX publishing: <http://e-editiones.ch/ontology/publishing#>
PREFIX delille: <http://e-editiones.ch/ontology/delille#>


# RETRIEVE CITING AND TRANSLATION EXPRESSIONS INCLUDING ARTICLES, WITH PARTITIONED PUBLICATION TIME:

SELECT DISTINCT ?partitionedlyPublishedExpression ?startYearStart ?startYearEnd ?endYearStart ?endYearEnd

WHERE {
	?partitionedlyPublishedExpression
		a ?Expression;
		publishing:isPublishedIn ?expressionPartitionedPublication.
	OPTIONAL {
		?partitionedlyPublishedExpression
			text-expression:isPartOfExpression ?articleTanslatedVersePoem.
		?articleTanslatedVersePoem a delille:TranslatedVersePoem
		}
	?expressionPartitionedPublication publishing:hasPartitionedPublishing ?partitionedPublishing.
	?partitionedPublishing
		publishing:hasStartYearPeriod ?startYearPeriod;
		publishing:hasEndYearPeriod ?endYearPeriod.
	?startYearPeriod
		calendar:hasGregorianStartDate ?startYearStart;
		calendar:hasGregorianEndDate ?startYearEnd.
	?endYearPeriod
		calendar:hasGregorianStartDate ?endYearStart;
		calendar:hasGregorianEndDate ?endYearEnd.
	}