PREFIX delille-research: <http://e-editiones.ch/ontology/delille-research#>

CONSTRUCT {
	?rhymingVerse
		delille-research:verseHasNumberOfEarlyScientificOrVulgarizedExpressionAndDictionaryCitations ?earlyScientificOrVulgarizedExpressionAndDictionaryCitationCount;
		delille-research:verseHasNumberOfLateNonScientificOrVulgarizedExpressionAndDictionaryCitations ?lateNonScientificOrVulgarizedExpressionAndDictionaryCitationCount;
		delille-research:verseHasNumberOfEarlyNonScientificOrVulgarizedExpressionAndDictionaryCitations ?earlyNonScientificOrVulgarizedExpressionAndDictionaryCitationCount;
		delille-research:verseHasNumberOfLateScientificOrVulgarizedExpressionAndDictionaryCitations ?lateScientificOrVulgarizedExpressionAndDictionaryCitationCount
	}

WHERE {
	?rhymingVerse
		delille-research:verseHasNumberOfEarlyScientificOrVulgarizedExpressionAndDictionaryCitations ?earlyScientificOrVulgarizedExpressionAndDictionaryCitationCount;
		delille-research:verseHasNumberOfLateNonScientificOrVulgarizedExpressionAndDictionaryCitations ?lateNonScientificOrVulgarizedExpressionAndDictionaryCitationCount;
		delille-research:verseHasNumberOfEarlyNonScientificOrVulgarizedExpressionAndDictionaryCitations ?earlyNonScientificOrVulgarizedExpressionAndDictionaryCitationCount;
		delille-research:verseHasNumberOfLateScientificOrVulgarizedExpressionAndDictionaryCitations ?lateScientificOrVulgarizedExpressionAndDictionaryCitationCount
	}
